// Curated GM reactions, informed by Unicode frequency data and verified against Emoji 12.0.
// Native Unicode text only; labels describe the intended use in this picker.
export const EMOJI_GROUPS = Object.freeze([
  { id: "faces", icon: "🙂", label: {"ru":"Смайлы","en":"Faces"}, items: [
    {"symbol":"😀","ru":"Радость","en":"Joy"},
    {"symbol":"😁","ru":"Широкая улыбка","en":"Big grin"},
    {"symbol":"😂","ru":"Смех до слёз","en":"Laughing tears"},
    {"symbol":"🤣","ru":"Хохот","en":"Roaring laughter"},
    {"symbol":"😊","ru":"Тёплая улыбка","en":"Warm smile"},
    {"symbol":"🙂","ru":"Лёгкая улыбка","en":"Gentle smile"},
    {"symbol":"😉","ru":"Подмигивание","en":"Wink"},
    {"symbol":"😍","ru":"Восхищение","en":"Adoration"},
    {"symbol":"😘","ru":"Воздушный поцелуй","en":"Blowing a kiss"},
    {"symbol":"😎","ru":"Крутость","en":"Feeling cool"},
    {"symbol":"🥳","ru":"Праздничное настроение","en":"Party mood"},
    {"symbol":"🤗","ru":"Объятия","en":"A hug"},
    {"symbol":"🤔","ru":"Размышление","en":"Pondering"},
    {"symbol":"🤨","ru":"Недоверие","en":"Scepticism"},
    {"symbol":"😐","ru":"Нейтральность","en":"Neutral mood"},
    {"symbol":"😑","ru":"Безучастность","en":"Indifference"},
    {"symbol":"🙄","ru":"Закатывание глаз","en":"Eye roll"},
    {"symbol":"😏","ru":"Усмешка","en":"A smirk"},
    {"symbol":"😒","ru":"Недовольство","en":"Displeasure"},
    {"symbol":"😔","ru":"Грусть","en":"Sadness"},
    {"symbol":"😢","ru":"Слеза","en":"A tear"},
    {"symbol":"😭","ru":"Рыдания","en":"Sobbing"},
    {"symbol":"😟","ru":"Беспокойство","en":"Worry"},
    {"symbol":"😨","ru":"Страх","en":"Fear"},
    {"symbol":"😱","ru":"Ужас","en":"Horror"},
    {"symbol":"😳","ru":"Смущение","en":"Embarrassment"},
    {"symbol":"😠","ru":"Злость","en":"Anger"},
    {"symbol":"😡","ru":"Ярость","en":"Rage"},
    {"symbol":"🤬","ru":"Ругань","en":"Cursing"},
    {"symbol":"😴","ru":"Сон","en":"Asleep"},
    {"symbol":"😷","ru":"Медицинская маска","en":"Wearing a mask"},
    {"symbol":"🤢","ru":"Тошнота","en":"Nausea"},
    {"symbol":"🤕","ru":"Травма","en":"Injury"},
    {"symbol":"😇","ru":"Невинность","en":"Innocence"},
    {"symbol":"😈","ru":"Злорадство","en":"Mischief"}
  ] },
  { id: "actions", icon: "👋", label: {"ru":"Действия","en":"Actions"}, items: [
    {"symbol":"👋","ru":"Приветствие","en":"Waving hello"},
    {"symbol":"✋","ru":"Поднятая ладонь","en":"Raised palm"},
    {"symbol":"🖐️","ru":"Раскрытая ладонь","en":"Spread fingers"},
    {"symbol":"👌","ru":"Всё хорошо","en":"All good"},
    {"symbol":"✌️","ru":"Жест победы","en":"Victory gesture"},
    {"symbol":"🤞","ru":"Скрещённые пальцы","en":"Fingers crossed"},
    {"symbol":"👍","ru":"Одобрение","en":"Approval"},
    {"symbol":"👎","ru":"Неодобрение","en":"Disapproval"},
    {"symbol":"👊","ru":"Кулак вперёд","en":"Fist forward"},
    {"symbol":"✊","ru":"Поднятый кулак","en":"Raised fist"},
    {"symbol":"🤝","ru":"Рукопожатие","en":"Shaking hands"},
    {"symbol":"👏","ru":"Аплодисменты","en":"Applause"},
    {"symbol":"🙌","ru":"Ликование","en":"Celebrating"},
    {"symbol":"👐","ru":"Открытые руки","en":"Open palms"},
    {"symbol":"🙏","ru":"Сложенные ладони","en":"Palms together"},
    {"symbol":"💪","ru":"Напряжённый бицепс","en":"Flexed arm"},
    {"symbol":"👈","ru":"Указать влево","en":"Point left"},
    {"symbol":"👉","ru":"Указать вправо","en":"Point right"},
    {"symbol":"👆","ru":"Указать вверх","en":"Point up"},
    {"symbol":"👇","ru":"Указать вниз","en":"Point down"},
    {"symbol":"☝️","ru":"Поднять указательный палец","en":"Raise index finger"},
    {"symbol":"🤚","ru":"Тыльная сторона ладони","en":"Back of hand"},
    {"symbol":"🤲","ru":"Ладони вверх","en":"Palms up"},
    {"symbol":"🤙","ru":"Жест «позвони»","en":"Call-me gesture"},
    {"symbol":"🤘","ru":"Жест «рок»","en":"Rock gesture"},
    {"symbol":"🙋","ru":"Поднять руку","en":"Raise a hand"},
    {"symbol":"🙅","ru":"Жест отказа","en":"Refusal gesture"},
    {"symbol":"🙆","ru":"Жест согласия","en":"Agreement gesture"},
    {"symbol":"🙇","ru":"Поклон","en":"Bowing"},
    {"symbol":"🤷","ru":"Пожать плечами","en":"Shrugging"},
    {"symbol":"🤦","ru":"Прикрыть лицо ладонью","en":"Facepalm"},
    {"symbol":"🚶","ru":"Идти","en":"Walking"},
    {"symbol":"🏃","ru":"Бежать","en":"Running"},
    {"symbol":"💃","ru":"Танцовщица","en":"Dancing woman"},
    {"symbol":"🕺","ru":"Танцор","en":"Dancing man"}
  ] },
  { id: "symbols", icon: "❗", label: {"ru":"Символы эмоций","en":"Emotion symbols"}, items: [
    {"symbol":"❗","ru":"Восклицание","en":"Exclamation"},
    {"symbol":"❕","ru":"Белое восклицание","en":"White exclamation"},
    {"symbol":"❓","ru":"Вопрос","en":"Question"},
    {"symbol":"❔","ru":"Белый вопрос","en":"White question"},
    {"symbol":"‼️","ru":"Двойное восклицание","en":"Double exclamation"},
    {"symbol":"⁉️","ru":"Вопрос с восклицанием","en":"Question and exclamation"},
    {"symbol":"✅","ru":"Галочка в квадрате","en":"Boxed check"},
    {"symbol":"☑️","ru":"Отмеченный флажок","en":"Checked box"},
    {"symbol":"✔️","ru":"Галочка","en":"Check"},
    {"symbol":"❌","ru":"Красный крест","en":"Red cross"},
    {"symbol":"❎","ru":"Крест в квадрате","en":"Boxed cross"},
    {"symbol":"✖️","ru":"Знак умножения","en":"Multiplication"},
    {"symbol":"➕","ru":"Плюс","en":"Plus"},
    {"symbol":"➖","ru":"Минус","en":"Minus"},
    {"symbol":"➗","ru":"Деление","en":"Division"},
    {"symbol":"⭕","ru":"Красное кольцо","en":"Red ring"},
    {"symbol":"🚫","ru":"Запрет","en":"Prohibition"},
    {"symbol":"⛔","ru":"Вход запрещён","en":"Do not enter"},
    {"symbol":"⚠️","ru":"Предупреждение","en":"Caution"},
    {"symbol":"💢","ru":"Знак гнева","en":"Anger mark"},
    {"symbol":"💥","ru":"Удар","en":"Impact"},
    {"symbol":"💫","ru":"Головокружение","en":"Dizziness"},
    {"symbol":"💦","ru":"Капли пота","en":"Sweat drops"},
    {"symbol":"💨","ru":"Порыв воздуха","en":"Gust of air"},
    {"symbol":"💤","ru":"Знак сна","en":"Sleep marks"},
    {"symbol":"💬","ru":"Облачко речи","en":"Speech bubble"},
    {"symbol":"💭","ru":"Облачко мысли","en":"Thought bubble"},
    {"symbol":"❤️","ru":"Сердце","en":"Heart"},
    {"symbol":"💔","ru":"Разбитое сердце","en":"Heartbreak"},
    {"symbol":"❣️","ru":"Сердце-восклицание","en":"Heart-shaped exclamation"},
    {"symbol":"💯","ru":"Сто баллов","en":"Perfect score"},
    {"symbol":"🔴","ru":"Красный круг","en":"Red circle"},
    {"symbol":"🔵","ru":"Синий круг","en":"Blue circle"},
    {"symbol":"🔶","ru":"Оранжевый ромб","en":"Orange diamond"},
    {"symbol":"🔷","ru":"Синий ромб","en":"Blue diamond"}
  ] },
  { id: "other", icon: "✨", label: {"ru":"Прочее","en":"Other"}, items: [
    {"symbol":"🔥","ru":"Огонь","en":"Flame"},
    {"symbol":"✨","ru":"Искры","en":"Sparkling"},
    {"symbol":"⭐","ru":"Звезда","en":"Star"},
    {"symbol":"🌟","ru":"Сияющая звезда","en":"Shining star"},
    {"symbol":"⚡","ru":"Молния","en":"Lightning"},
    {"symbol":"❄️","ru":"Снежинка","en":"Snow crystal"},
    {"symbol":"☀️","ru":"Солнце","en":"Sun"},
    {"symbol":"🌙","ru":"Месяц","en":"Crescent"},
    {"symbol":"☁️","ru":"Облако","en":"Cloud"},
    {"symbol":"🌧️","ru":"Дождь","en":"Rain"},
    {"symbol":"🌪️","ru":"Смерч","en":"Whirlwind"},
    {"symbol":"🌈","ru":"Радуга","en":"Rainbow"},
    {"symbol":"💧","ru":"Капля","en":"Drop"},
    {"symbol":"🍀","ru":"Клевер удачи","en":"Lucky clover"},
    {"symbol":"💀","ru":"Череп","en":"Skull"},
    {"symbol":"👀","ru":"Глаза","en":"Eyes"},
    {"symbol":"👂","ru":"Ухо","en":"Ear"},
    {"symbol":"🧠","ru":"Мозг","en":"Brain"},
    {"symbol":"💡","ru":"Лампочка","en":"Light bulb"},
    {"symbol":"🔔","ru":"Колокольчик","en":"Bell"},
    {"symbol":"🔕","ru":"Выключенный звонок","en":"Muted bell"},
    {"symbol":"📣","ru":"Мегафон","en":"Megaphone"},
    {"symbol":"🚨","ru":"Сирена","en":"Siren"},
    {"symbol":"🎵","ru":"Нота","en":"Music note"},
    {"symbol":"🎶","ru":"Ноты","en":"Music notes"},
    {"symbol":"🎉","ru":"Хлопушка","en":"Confetti popper"},
    {"symbol":"🎭","ru":"Театральные маски","en":"Theatre masks"},
    {"symbol":"🎲","ru":"Игральная кость","en":"Die"},
    {"symbol":"🎯","ru":"Мишень","en":"Target"},
    {"symbol":"🏆","ru":"Кубок","en":"Trophy"},
    {"symbol":"👑","ru":"Корона","en":"Crown"},
    {"symbol":"💰","ru":"Мешок денег","en":"Money bag"},
    {"symbol":"🔑","ru":"Ключ","en":"Key"},
    {"symbol":"⚔️","ru":"Скрещённые мечи","en":"Crossed blades"},
    {"symbol":"🛡️","ru":"Щит","en":"Shield"}
  ] }
]);
