// User documentation belongs to Master screen; Generics only displays it.
import { OBJECT_HELP_PAGES, OBJECT_HELP_SETTINGS } from "./object-help-content.js";
const section = (id, ru, en, bodyRu, bodyEn) => ({ id, ru, en, bodyRu, bodyEn });
const page = (id, ru, en, sections) => ({ id, ru, en, sections });
export const SCREEN_HELP_PAGES = [
  ...OBJECT_HELP_PAGES,
  page("start", "Подготовить сцену к игре", "Prepare a scene for play", [
    section("prepare", "Карта и участники", "Map and participants", "Создайте сцену, добавьте карту и НИП обычными средствами Foundry. Откройте эту карту и выберите категорию 🎬 Ширма, затем «Ширма (панель)» или «Ширма (окно)». В верхней строке включите «Конструктор». Новая сцена не содержит схем: без автоматизации она может оставаться пустой.", "Create a scene, add its map and NPCs with Foundry, then view that map. Select the 🎬 Master screen category and choose Master screen (panel) or Master screen (window). Choose Constructor in the top bar. New scenes have no schemes and may remain without automation."),
    section("episodes", "От подготовки к запуску", "From preparation to play", "Для автоматизации нажмите «Создать схему»: она появится с одним эпизодом. Эпизод хранит подготовленное поведение и оформление. Например, добавьте состояния «Спокойствие», «Напряжение», «Тревога» и «Остановка». Сохранение не запускает действия. Для запуска перейдите в «Режиссёр» и выберите эпизод.", "Choose Create scheme to prepare automation; it starts with one episode. Episodes contain prepared behavior and appearance. For example, add Calm, Tension, Alarm and Stop states. Saving does not execute actions. Open Director and choose an episode to start it."),
    section("next", "Что настроить дальше", "Next steps", '<a data-help-page="constructor">Переходы эпизодов</a> · <a data-help-page="npc">Поведение НИП</a> · <a data-help-page="stop">Ручное управление</a>', '<a data-help-page="constructor">Episode transitions</a> · <a data-help-page="npc">NPC behavior</a> · <a data-help-page="stop">Manual control</a>')
  ]),
  page("constructor", "Подготовить эпизоды", "Prepare episodes", [
    section("window", "Перенести Ширму на другой монитор", "Move Master screen to another monitor", "Выберите «Ширма (окно)» или кнопку отделения в верхней строке. Если браузер блокирует открытие, разрешите всплывающие окна для адреса Foundry. Закрытие внешнего окна возвращает панель и сохраняет ввод; собственная кнопка × закрывает инструменты Ширмы.", "Choose Master screen (window) or the detach button in the top bar. If the browser blocks it, allow popups for the Foundry address. Closing the browser window returns the panel and keeps edits; Master screen's own × button closes its tools."),
    section("panel", "Освободить карту", "Keep the map clear", "В верхней строке выберите панель или отдельное окно браузера, затем вертикальное или горизонтальное расположение. Перетаскивайте выделенную внешнюю границу панели и границу её двух зон. Размеры сохраняются после закрытия и перезагрузки. Шестерёнка управляет видимостью вкладок.", "Use the top bar to choose a panel or separate browser window, then vertical or horizontal layout. Drag the marked outer panel divider and the divider between its two areas. Sizes survive closing and reloading. The gear controls visible tabs."),
    section("graph", "Разделить сцену на схемы", "Divide the scene into schemes", "На вкладке «Сцена» создайте схему с первым эпизодом. Каждая схема независимо управляет своей группой объектов. Кликните в любом месте строки дерева: настройки появятся в «Параметрах». Имена схем различаются в сцене, эпизодов — внутри схемы. Можно удалить все схемы, но последний эпизод существующей схемы удалить нельзя.", "On Scene, create a scheme with its first episode. Each scheme independently controls its own objects. Click anywhere in a tree row to show its Parameters. Scheme names are unique in the scene and episode names within their scheme. You may delete every scheme, but cannot delete the last episode of an existing scheme."),
    section("tabs", "Оставить нужные инструменты под рукой", "Keep useful tools at hand", "«Инструменты» открывают «Магазины» и «Диалоги», «Автоматизация» — «События», «Макросы» и «Источники». Категории только раскрывают меню. Если вкладки не помещаются, листайте стрелками. Шестерёнка открывает дерево с флажками: снятие флажка категории скрывает её дочерние вкладки. Каждая вкладка помнит собственный выбор; без выбора дополнительная зона пуста.", "Tools opens Shops and Dialogues; Automation opens Events, Macros and Sources. Categories only reveal their menu. Use the arrows when tabs overflow. The gear opens a tree of checkboxes: hiding a category hides its descendants. Each tab remembers its own selection; without a selection, the secondary area is empty."),
    section("descriptions", "Напомнить себе смысл подготовки", "Record what the preparation means", "Заполните «Описание» схемы, эпизода, события или триггера. У полей триггера поясните, что означает передаваемое значение. Встроенные определения уже содержат пояснения. Текст описания помогает ориентироваться и сам по себе не выполняет действий.", "Fill in the Description of a scheme, episode, event or trigger. Describe what each trigger field's value means. Built-in definitions already include explanations. Descriptions help you navigate preparation and never execute actions by themselves."),
    section("badges", "Проверить состояние одним взглядом", "Check the current state at a glance", "Задайте схеме один символ, например эмоджи. Значки рядом с именем сцены в Ширме и сверху кнопок сцен Foundry окрашены цветами текущего эпизода. Наведите курсор, чтобы прочитать название схемы и эпизода. «Не запущена» и «Остановлена» обозначаются отдельно; выбор эпизода в Конструкторе не меняет исполняемое состояние.", "Give each scheme one symbol, such as an emoji. Badges beside the scene name in Master screen and above Foundry scene buttons use the current episode's colors. Hover to read the scheme and episode names. Not started and Stopped are indicated separately; selecting an episode in Constructor does not change the running state."),
    section("order", "Упорядочить подготовку", "Organize the preparation", "Перетаскивайте строки, чтобы изменить порядок. При переносе эпизода в другую схему выберите копирование или перемещение. Цвет фона и текста помогают различать строки; задайте цвет кодом #RRGGBB или через палитру.", "Drag rows to reorder them. When dragging an episode to another scheme, choose copy or move. Background and text colors help distinguish rows; enter #RRGGBB or use the palette."),
    section("transitions", "Разрешить автоматический переход", "Allow an automatic transition", "В параметрах эпизода добавьте существующее событие в таблицу «События». При его возникновении схема перейдёт в этот эпизод. Одно событие может вести только в один эпизод одной схемы. Мастер в Режиссёре может перейти в любой эпизод без этих ограничений.", "Add an existing event to the episode's Events table. When it occurs, the scheme enters this episode. One event can target only one episode per scheme. In Director, the GM may enter any episode without these restrictions."),
    section("scene", "Найти остальные настройки", "Find the remaining settings", "На вкладке «Иное» выберите нужный блок: его содержимое откроется в дополнительной зоне. Здесь находятся ещё не распределённые по отдельным вкладкам инструменты НИП, карты, взаимодействий и рабочих окон. Перед сменой карты сохраните подготовку.", "On Other, select a block to show its contents in the secondary area. This contains NPC, map, interaction and workspace tools awaiting their own tabs. Save your preparation before switching maps.")
  ]),
  page("events", "Связать события и реакции", "Connect events and reactions", [
    section("create", "Задать событие сцены", "Define a scene event", "На вкладке «События» создайте событие с уникальным именем. Оно обозначает происходящее в сцене: например, поднятую тревогу. Под ним видны триггеры — варианты вызова с заранее описанными данными. Выберите строку, чтобы настроить её в «Параметрах».", "On Events, create an event with a unique name. It describes something happening in the scene, such as an alarm. Its child triggers are invocation types with predefined data fields. Select a row to edit it in Parameters."),
    section("fields", "Подготовить данные вызова", "Prepare invocation data", "У триггера задайте уникальное в сцене имя, связанное событие и поля. Для строки укажите длину, для целого или дробного числа — границы, для дробного — допустимое число знаков после запятой. Логическое поле принимает да или нет. Неподходящие данные не запускают событие.", "Give a trigger a scene-wide unique name, a linked event and fields. Set length limits for text, bounds for integers or decimals, and decimal precision where needed. A boolean field accepts true or false. Invalid data does not run the event."),
    section("subscribers", "Выполнить реакции по порядку", "Run reactions in order", "Добавьте к событию подписчиков: встроенное действие, макрос или вызов другого триггера с заданными значениями. Их порядок определяет порядок выполнения. Затем назначьте событие нужному эпизоду, если оно должно переключать схему. Избегайте круговых вызовов: цепочка с чрезмерной глубиной останавливается.", "Add subscribers to an event: a built-in action, a macro or another trigger with fixed values. Their order determines execution order. Assign the event to an episode if it should switch a scheme. Avoid circular invocations: chains that grow too deep are stopped."),
    section("builtins", "Использовать готовые события", "Use built-in events", "Встроенные события и триггеры доступны для вызова, но их нельзя переименовать или удалить. Для собственного набора данных создайте пользовательский вариант. Импорт и экспорт рядом с выбранным объектом переносят его подготовку в JSON.", "Built-in events and triggers may be invoked but cannot be renamed or deleted. Create a custom entry for your own data fields. Import and export beside the selected object transfer its preparation as JSON.")
  ]),
  page("macros", "Подключить макрос к событию", "Attach a macro to an event", [
    section("prepare", "Подготовить макрос в Foundry", "Prepare the macro in Foundry", "Создайте или отредактируйте макрос обычным окном Foundry. Добавьте его в подписчики нужного события перетаскиванием. Используйте проверенные вами макросы: они могут менять документы мира.", "Create or edit a macro in Foundry's normal macro window. Drag it into the event's subscribers. Use macros you have checked: they can change world documents."),
    section("review", "Проверить связь перед игрой", "Check the connection before play", "На вкладке «Макросы» видны макросы, используемые Ширмой. Выберите макрос, чтобы увидеть принимаемые триггеры в дополнительной зоне. Проверьте поля и значения триггера, затем испытайте событие на подготовленной сцене. Аварийная остановка не отменяет уже начатый сторонний макрос.", "The Macros tab lists macros used by Master screen. Select one to see accepted triggers in the secondary area. Check their fields and values, then try the event on a prepared scene. Emergency stop cannot undo an external macro that has already started.")
  ]),
  page("npc", "Оживить НИП", "Bring NPCs to life", [
    section("calm", "Реплики и торговля", "Speech and trading", "В Конструкторе кликните НИП. Периодические фразы пока настраиваются через «Поведение токена (техдолг)»: задайте интервал и дальность. Магазин создайте в «Инструменты → Магазины», затем назначьте через «Поведение → Особенности». Для постоянного допуска выберите повторение «Каждый раз».", "Click an NPC in Constructor. Recurring speech is still configured in Token behavior (legacy): set its interval and range. Create the shop in Tools → Shops, then attach it through Behavior → Features. Choose Every time for recurring admission."),
    section("tension", "Предупреждение и патруль", "Warning and patrol", "В «Напряжении» задайте эмоджи и однократную реплику. Включите патрулирование, укажите скорость и добавьте точки кликами по карте. Поведения предыдущего эпизода прекращаются при переходе.", "In Tension, set an emoji and an entry line. Enable patrol, choose a speed and add waypoints by clicking the map. The previous episode's behaviors end on transition."),
    section("alarm", "Тревога и подкрепление", "Alarm and reinforcements", "В «Тревоге» включите паузу, выберите звук и добавьте подкрепление из списка персонажей. Укажите места и число НИП. В Режиссёре кнопка «Бой и инициатива» помогает подготовить бой. Завершение боя не выбирает следующий эпизод за мастера.", "In Alarm, enable pause, choose a sound and drag reinforcements from the Actors list. Set their positions and counts. In Director, Combat and initiative helps prepare combat. Ending combat does not choose the next episode for you.")
  ]),
  page("director", "Вести сцену", "Run the scene", [
    section("transition", "Переключить эпизод", "Switch episodes", "В верхней строке Ширмы включите «Режиссёр». Выберите схему и нужный эпизод, затем выполните переход. Мастер может перейти в любой эпизод. Явный повторный вход заново применяет подготовленные позиции, окна и разовые действия; перезагрузка Foundry этого не делает. Другие схемы продолжают свою работу.", "Choose Director in the Master screen top bar. Select a scheme and episode, then perform the transition. The GM may enter any episode. Explicit re-entry reapplies prepared positions, windows and entry actions; reloading Foundry does not. Other schemes continue their work."),
    section("manual", "Вмешаться в игру", "Intervene in play", "Перемещайте токены и окна по ходу игры. Чтобы патруль не вернул НИП под управление, нажмите «Отключить» рядом с ним. Это отключение сохраняется между эпизодами до вашего прямого включения.", "Move tokens and windows as play unfolds. Press Disable beside an NPC to prevent its patrol from taking control again. This override persists across episodes until you explicitly enable it."),
    section("observe", "Проверить происходящее", "Check what is happening", "В Режиссёре доступны счётчики триггеров и журнал событий. Окна «Магазины» и «Диалоги и действия» позволяют подключиться к взаимодействию и прочитать нужную реплику.", "Director provides trigger counters and the event log. Shops and Dialogues and actions let you join an interaction or read the relevant line.")
  ]),
  page("stop", "Остановить автоматизацию", "Stop automation", [
    section("emergency", "Вернуть сцену под ручное управление", "Take manual control", "Нажмите заметную кнопку «Остановить всё» в Режиссёре. Остановка сохраняется, а положение, здоровье и предметы остаются как есть. Закрытие окон Ширмы само по себе не останавливает сцену.", "Press Stop all in Director. The stop persists and positions, health and items remain as they are. Closing Master screen windows does not itself stop the scene."),
    section("resume", "Продолжить с выбранного момента", "Resume from a chosen point", "Выберите схему и эпизод возобновления, затем явно запустите их. Это новый вход: реплика, звук и подкрепление могут выполниться снова. Можно остановить одну схему, оставив остальные в работе; после общей остановки возобновляйте только нужные схемы.", "Select a scheme and resume episode, then explicitly start them. This is a new entry: speech, sound and reinforcements may run again. You may stop one scheme while the others keep running; after a scene-wide stop, resume only the schemes you need."),
    section("facts", "После боя", "After combat", "При необходимости вручную перейдите в эпизод «Остановка». Он не лечит НИП, не возвращает товары и не убирает созданное подкрепление. Уже выполненные действия и начатый сторонний макрос кнопка остановки не отменяет.", "If appropriate, manually enter the Stop episode. It does not heal NPCs, restore goods or remove spawned reinforcements. The stop button cannot undo completed actions or cancel an already-running external macro.")
  ]),
  page("trade", "Провести обмен", "Trade items", [
    section("prepare", "Открыть магазин", "Open a shop", "Подведите своего персонажа к НИП и выберите взаимодействие магазина. Слева видны НИП и ассортимент; в зоне торговли подготовьте отдельно предложение персонажа и предложение магазина.", "Move your character near the NPC and choose its shop interaction. The NPC and catalog appear on the left; prepare the character's and shop's offers separately in the trade area."),
    section("confirm", "Подтвердить сделку", "Confirm the trade", "До подтверждения вещи остаются на своих местах. Нельзя предложить чужие вещи или отсутствующий товар. Один магазин обслуживает одного игрока с одним персонажем. Если нужно одобрение, отправьте запрос мастеру; иначе завершите обмен самостоятельно.", "Items stay in place until confirmation. You cannot offer another character's belongings or unavailable stock. A shop serves one player with one character at a time. Request GM approval when required, or complete the trade yourself."),
    section("gm", "Помочь игроку", "Assist a player", "В Режиссёре откройте «Магазины», выберите текущую сделку и подключитесь к ней. Без поддержки денежной системы цены и валюта не показываются; передаются целые предметы, включая заданное системой количество внутри них.", "In Director, open Shops and join the current trade. Without currency support, prices and money are hidden; complete items are transferred, including any quantity stored in them by the game system.")
  ]),
  page("dialogues", "Дать игроку взаимодействие", "Give players an interaction", [
    section("prepare", "Подготовить разговор или предмет", "Prepare a conversation or object", "Создайте диалог в «Инструменты → Диалоги»: заполните блоки, изображения и ответы. Затем назначьте его НИП или тайлу через «Поведение → Особенности» и задайте условия. Клик игрока по объекту покажет пункт «Диалог», когда есть допуск. «Уйти» доступно всегда и не выполняет событие завершения.", "Create a dialogue in Tools → Dialogues and fill its blocks, images and replies. Attach it to an NPC or tile through Behavior → Features and set conditions. Clicking the object shows Dialogue when admission passes. Leave is always available and does not emit a completion event."),
    section("action", "Обойтись без разговора", "Act without a conversation", "Добавьте прямое действие, например «Потянуть рычаг». Оно отправит указанное событие сразу. Ниже настройте реакцию на то же имя события: переход, макрос или сообщение в чат.", "Add a direct action such as Pull the lever. It emits the chosen event immediately. Add a reaction using the same event name: a transition, macro or chat message."),
    section("manual", "Зачитать или показать вручную", "Read or show it manually", "В Режиссёре откройте «Диалоги и действия». Просматривайте и зачитывайте страницы или покажите диалог выбранным игрокам, даже после остановки автоматизации. Ручной показ не запускает события и не возобновляет сцену.", "Open Dialogues and actions in Director. Read pages yourself or show a dialogue to selected players, even while automation is stopped. Manual presentations do not emit events or resume the scene.")
  ]),
  page("triggers", "Ограничить лишние срабатывания", "Limit unwanted triggers", [
    section("tags", "Различать участников", "Distinguish participants", "В Конструкторе задайте токенам и тайлам теги через запятую. Триггер проверяет теги действующего персонажа: достаточно одного разрешающего тега, но любой запрещающий отменяет допуск. Пустые списки не ограничивают запуск.", "Assign comma-separated tags to tokens and tiles in Constructor. A trigger checks the acting character's tags: one allowed match is enough, but any denied match excludes it. Empty lists do not restrict activation."),
    section("count", "Не повторять одно событие без нужды", "Avoid needless repetition", "По умолчанию разрешён один запуск. Для постоянных взаимодействий выберите «Каждый раз». Сброс при новом входе задаётся отдельно; переподключение счётчик сохраняет. Новый разговор или торговая сессия расходует один запуск, продолжение — нет.", "One activation is allowed by default. Choose Every time for recurring interactions. Reset on entry is a separate option; reconnecting preserves the counter. A new conversation or trade session uses one activation; continuing it does not."),
    section("reset", "Разрешить ещё одну попытку", "Allow another attempt", "В Режиссёре раскройте «Допуск и счётчики триггеров». Сбросьте нужный счётчик или вручную включите/выключите триггер. Ручное включение не отменяет ограничения по тегам и эпизодам.", "Expand Trigger permissions and counters in Director. Reset a counter or manually enable or disable a trigger. Manual enabling does not bypass tag or episode restrictions.")
  ]),
  page("workspace", "Подготовить рабочие окна", "Prepare workspace windows", [
    section("plan", "Показать нужные документы", "Show the right documents", "В эпизоде перетащите документы в «Рабочий стол мастера» или «Окна игроков», либо возьмите расположение открытых листов. У игроков откроются только доступные им документы: права задаются в Foundry.", "Drag documents into the episode's GM workspace or Player windows, or capture the positions of open sheets. Players only see documents they may access; permissions are set in Foundry."),
    section("during", "Передвинуть во время игры", "Move windows during play", "Меняйте расположение вручную. Подготовленные позиции возвращаются при новом входе в эпизод, а при переподключении сохраняется текущее расположение. Ранее открытые вами листы Ширма не закрывает.", "Adjust positions during play. Prepared positions return on a new episode entry; reconnecting retains the current layout. Master screen does not close sheets you had already opened yourself."),
    section("appearance", "Выбрать удобный вид", "Choose an appearance", "В настройках Foundry откройте dmicher 🧰 Generics: общая тема и поведение окон действуют для всех окон dmicher у вас. Прилипание помогает выровнять окна. Чтобы переместить сцепленные окна вместе, тяните заголовок одного из них правой кнопкой мыши; эту возможность можно отключить в Generics. Сохранение оформления оставляет окно настроек открытым.", "Open dmicher 🧰 Generics in Foundry settings. The shared theme and window behavior apply to all your dmicher windows. Snapping helps align windows. To move attached windows together, drag one of their headers with the right mouse button; this can be disabled in Generics. Saving appearance keeps the settings window open.")
  ]),
  page("actor", "Посмотреть глазами персонажа", "Preview a character's view", [
    section("view", "Проверить доступное взаимодействие", "Check available interactions", "Откройте «Актёр» и выберите персонажа игрока. Предпросмотр учитывает его зрение и доступные взаимодействия. Это вспомогательный вид: тайлы, эффекты освещения и исследованный туман могут отличаться от клиента игрока.", "Open Actor and select a player character. The preview uses their vision and available interactions. It is a simplified view: tiles, lighting effects and explored fog may differ from the player's client."),
    section("display", "Второй экран", "Second display", "В Foundry 14 можно отделить окно штатной кнопкой и переместить его на второй экран. В Foundry 13 штатного отделения нет.", "In Foundry 14, use the native detach button to move the window to a second display. Foundry 13 does not provide native window detachment.")
  ]),
  page("transfer", "Перенести подготовленную сцену", "Transfer a prepared scene", [
    section("export", "Сохранить подготовку", "Save the preparation", "Чтобы перенести всю сцену, выберите её экспорт JSON в «Иное». Файл содержит сцену, эпизоды и связанные персонажи, журналы и макросы. Для отдельной схемы, эпизода, события или триггера используйте импорт/экспорт в его параметрах. Карты, изображения и звуки перенесите отдельно; ссылки на документы и объекты другой сцены проверьте после импорта.", "To transfer the whole scene, use its JSON export under Other. The file contains the scene, episodes and linked Actors, Journals and Macros. To transfer one scheme, episode, event or trigger, use import/export in its Parameters. Transfer maps, images and sounds separately; check references to documents and objects from another scene after importing."),
    section("import", "Проверить перед запуском", "Check before running", "В другом мире той же игровой системы выберите «Импорт JSON». Создаются отдельные документы, а сцена не запускается автоматически. Проверьте изображения, ссылки, права и используемые макросы, затем включите нужный эпизод вручную.", "Choose Import JSON in another world using the same game system. Separate documents are created and the scene does not start automatically. Check images, links, permissions and any macros, then start the desired episode manually.")
  ]),
  page("author", "Автор", "Author", [section("contact", "dmicher abathur kubrow", "dmicher abathur kubrow", 'Сообщить о проблеме или предложить улучшение можно на <a href="https://github.com/dkubrow-dev/dmicher-master-screen/issues" target="_blank" rel="noopener noreferrer">странице Ширмы</a>. Опишите действие и результат, укажите версию Foundry.', 'Use the <a href="https://github.com/dkubrow-dev/dmicher-master-screen/issues" target="_blank" rel="noopener noreferrer">Master screen issue tracker</a> to report a problem or suggest an improvement. Include the action, its result and your Foundry version.')]),
  page("thanks", "Благодарности", "Thanks", [section("community", "Участникам игр и проверки", "Players and testers", "Спасибо мастерам и игрокам, которые проверяют Ширму в своих играх и делятся конкретными примерами. Такие наблюдения помогают уменьшать рутину за столом.", "Thank you to GMs and players who test Master screen in their games and share concrete examples. Your observations help reduce routine work at the table.")]),
  page("modules", "Модули dmicher", "dmicher modules", [
    section("screen", "🎬 Master screen — Ширма мастера", "🎬 Master screen", "Готовьте эпизоды и реакции объектов, затем ведите сцену и вмешивайтесь в её события. Ширма берёт на себя подготовленную рутину, сохраняя решения за мастером.", "Prepare episodes and object reactions, then run the scene and intervene in its events. Master screen handles the prepared routine while decisions remain with the GM."),
    section("spotlight", "dmicher 🎥 Spotlight Tools — внимание участников", "dmicher 🎥 Spotlight Tools — participant attention", "Следите за заявками, распределением внимания и временем ожидания. Опросы готовности и таймеры помогают организовать игру и перерывы.", "Track requests, attention and waiting time. Readiness polls and timers help organize play and breaks."),
    section("generics", "dmicher 🧰 Generics — общие инструменты", "dmicher 🧰 Generics — shared tools", "Выберите единую тему и удобное поведение окон dmicher в настройках Generics. Там же включается приветствие со списком активных модулей, справкой и настройками. Общий Информатор отправляет приветствие и сообщения подключённых модулей.", "Choose a shared theme and window behavior in Generics settings. Enable the welcome with active modules, help and settings links there too. The shared Informer sends the welcome and messages from connected modules."),
    section("premium", "Premium — дополнительные возможности", "Premium — additional features", "Если нужны дополнительные возможности, введите лицензию в настройках Premium и проверьте список доступных модулей. Например, доступ к Generics позволяет импортировать собственные стили. Основная работа Ширмы и Spotlight не требует Premium; сохранённые дополнительные настройки остаются после окончания доступа.", "If you need additional features, enter your license in Premium settings and check the available modules. For example, Generics access enables custom style import. Core Master screen and Spotlight features do not require Premium; saved extra settings remain when access expires."),
    section("licences", "Сервер лицензий", "License server", "Проверяет лицензию и предоставляет сведения о доступе и выпусках. Он работает вне игрового мира; устанавливать его как модуль Foundry не нужно.", "Verifies licenses and supplies access and release information. It operates outside your game world; you do not install it as a Foundry module.")
  ])
];

// [field name (or a selector), anchor, RU label, EN label, RU hint, EN hint].
export const SCREEN_HELP_SETTINGS = [
  ...OBJECT_HELP_SETTINGS,
  { id: "settings-scheme", ru: "Схема и оформление строк", en: "Schemes and row appearance", fields: [
    ['[data-ide-parameters] [name="schemeName"]', "name", "Название схемы", "Scheme name", "Уникальное в сцене название независимой группы эпизодов. Переименование не запускает схему.", "A scene-wide unique name for an independent group of episodes. Renaming does not start the scheme."],
    ["schemeSymbol", "symbol", "Символ схемы", "Scheme symbol", "Один видимый символ, в том числе составной эмоджи. Он обозначает схему в заголовке Ширмы и на кнопке сцены; цвет значка определяется текущим эпизодом.", "One visible symbol, including a compound emoji. It identifies the scheme in Master screen and on the scene button; its color follows the current episode."],
    ['[data-ide-parameters] [name="description"]', "description", "Описание", "Description", "Поясните назначение выбранной схемы, эпизода, события или триггера. Описание сохраняется вместе с объектом, не запускает действий и переносится при экспорте JSON.", "Explain the purpose of the selected scheme, episode, event or trigger. The description is saved with the object, executes no actions and is included in JSON exports."],
    ['[data-ide-parameters] [name="background"]', "background", "Цвет фона", "Background color", "Фон выбранной схемы или эпизода в списках и Режиссёре. Введите #RRGGBB или выберите цвет в палитре.", "The selected scheme or episode's background in lists and Director. Enter #RRGGBB or choose a color from the palette."],
    ['[data-ide-parameters] [name="textColor"]', "text", "Цвет текста", "Text color", "Цвет названия схемы или эпизода. Подберите заметное сочетание с фоном; поле и палитра показывают один цвет.", "The scheme or episode name color. Choose a readable contrast with its background; the field and palette show the same color."]
  ] },
  { id: "settings-catalog", ru: "События и подписчики", en: "Events and subscribers", fields: [
    ['[data-ide-parameters] [name="eventName"]', "name", "Название события", "Event name", "Уникальное имя события в этой сцене. Используйте его при выборе реакции и перехода эпизода.", "A unique event name in this scene. Use it when choosing reactions and episode transitions."],
    ["subscriberKind", "kind", "Тип подписчика", "Subscriber type", "Выберите макрос, встроенное действие или вызов другого триггера. Подписчики выполняются в заданном порядке.", "Choose a macro, built-in action or another trigger invocation. Subscribers run in the specified order."],
    ["subscriberMacro", "macro", "Макрос", "Macro", "Макрос Foundry, который получит данные вызвавшего триггера. Проверьте его перед использованием на игре.", "The Foundry macro that receives the invoking trigger's data. Check it before using it during play."],
    ["subscriberTrigger", "trigger", "Триггер", "Trigger", "Зарегистрированный тип вызова другого события. Его поля определяют допустимые статические значения.", "A registered invocation type for another event. Its fields determine valid fixed values."],
    ["subscriberAction", "action", "Встроенное действие", "Built-in action", "Выберите действие Ширмы, которое нужно выполнить при событии. Переход эпизода задаётся в его таблице событий.", "Choose the Master screen action to run for the event. Set episode transitions in the episode's Events table."],
    ["subscriberScheme", "scheme", "Схема", "Scheme", "Схема, к которой относится выбранное встроенное действие. Остановка одной схемы не останавливает другие.", "The scheme affected by the chosen built-in action. Stopping one scheme does not stop the others."],
    ["subscriberParameters", "parameters", "Статические параметры", "Fixed parameters", "Значения полей вызываемого триггера в JSON. Строки пишутся в кавычках, числа без кавычек, логические значения — true или false. Неверные значения не сохраняются.", "Values for the invoked trigger's fields as JSON. Quote strings, leave numbers unquoted, and use true or false for booleans. Invalid values cannot be saved."],
    ["subscriberText", "text", "Текст сообщения", "Message text", "Сообщение для выбранной аудитории при выполнении подписчика. Текст не исполняется как код.", "A message for the chosen audience when this subscriber runs. Text is not executed as code."],
    ["subscriberGMs", "gms", "Мастера", "GMs", "Добавить мастеров к получателям сообщения.", "Include GMs among the message recipients."],
    ["subscriberInteractor", "interactor", "Взаимодействующий игрок", "Interacting player", "Добавить участника, чьё взаимодействие породило событие, если он определён.", "Include the participant whose interaction produced the event, when known."],
    ["subscriberNearby", "nearby", "Игроки рядом", "Nearby players", "Добавить игроков с персонажами возле объекта события в указанном радиусе.", "Include players with characters near the event's object within the chosen range."],
    ["subscriberRange", "range", "Дальность", "Range", "Радиус выбора игроков рядом в единицах расстояния сцены.", "The nearby-player radius in scene distance units."],
    ["subscriberVisible", "visible", "Учитывать видимость", "Require visibility", "Для игроков рядом дополнительно проверять видимость объекта; стены могут исключить персонажа из аудитории.", "For nearby players, also check visibility of the object; walls may exclude a character from the audience."]
  ] },
  { id: "settings-typed-trigger", ru: "Данные триггера", en: "Trigger data", fields: [
    ["triggerName", "name", "Название триггера", "Trigger name", "Уникальное в сцене имя типа вызова. Оно отличается от ручного флага допуска взаимодействия.", "A scene-wide unique invocation type name. It is separate from an interaction's manual activation flag."],
    ["triggerEventId", "event", "Событие", "Event", "Событие, которое принимает этот триггер и выполняет свои реакции.", "The event that accepts this trigger and runs its reactions."],
    ["parameterName", "field", "Имя параметра", "Parameter name", "Имя поля данных: латинские буквы, цифры и подчёркивание; первый знак — буква или подчёркивание. Имена полей не повторяются.", "The data field name: Latin letters, digits and underscores, starting with a letter or underscore. Field names must be unique."],
    ["parameterDescription", "description", "Описание параметра", "Parameter description", "Поясните, что означает значение поля и когда оно используется. Это подсказка для подготовки, она не изменяет проверку значения.", "Explain what the field's value means and when it is used. This preparation note does not change value validation."],
    ["parameterType", "type", "Тип параметра", "Parameter type", "Строка, целое число, дробное число или логическое значение. Значения другого типа отклоняются.", "Text, integer, decimal or boolean. Values of a different type are rejected."],
    ['[data-ide-parameters] [name="minLength"]', "min-length", "Минимальная длина", "Minimum length", "Минимальное число символов строки. Пустое поле не задаёт нижнюю границу.", "The minimum text length. An empty field sets no lower bound."],
    ['[data-ide-parameters] [name="maxLength"]', "max-length", "Максимальная длина", "Maximum length", "Максимальное число символов строки. Не может быть меньше минимальной длины.", "The maximum text length. It cannot be less than the minimum."],
    ['[data-ide-parameters] [name="min"]', "min", "Минимальное значение", "Minimum value", "Нижняя включительная граница числа. Пустое поле не ограничивает минимум.", "The inclusive lower numeric bound. An empty field sets no minimum."],
    ['[data-ide-parameters] [name="max"]', "max", "Максимальное значение", "Maximum value", "Верхняя включительная граница числа. Она не может быть меньше минимума.", "The inclusive upper numeric bound. It cannot be less than the minimum."],
    ["decimals", "decimals", "Знаков после запятой", "Decimal places", "Допустимое число десятичных знаков дробного числа, от 0 до 12. Значение с лишними знаками отклоняется, а не округляется.", "Allowed decimal places, from 0 to 12. Values with excess precision are rejected, not rounded."],
    ["macroTrigger", "macro-trigger", "Принимаемый триггер", "Accepted trigger", "Тип данных, с которым связан выбранный макрос в Ширме. Сверьте поля триггера с ожидаемыми данными макроса.", "The data type linked to the selected macro in Master screen. Check its fields against the data expected by the macro."]
  ] },
  { id: "settings-episode", ru: "Настройки эпизода", en: "Episode settings", fields: [
    ["name", "name", "Название", "Name", "Уникальное внутри схемы имя эпизода в дереве сцены и Режиссёре.", "The episode's name in the Scene tree and Director, unique within its scheme."],
    ["newEpisodeEvent", "event", "Событие перехода", "Transition event", "Добавьте событие, которое автоматически переводит схему в выбранный эпизод. Одно событие не может вести в два эпизода одной схемы. Ручной выбор мастера не ограничивается.", "Add an event that automatically moves the scheme to this episode. One event cannot target two episodes in the same scheme. Manual GM selection is unrestricted."],
    ["stop", "stop", "Остановка автоматизации", "Stop automation", "Эпизод оставляет игру под ручным управлением без реплик, движения и входных действий. Состояние мира сохраняется.", "This episode leaves play under manual control without speech, movement or entry actions. The world's state is preserved."],
    ["pause", "pause", "Поставить Foundry на паузу", "Pause Foundry", "Ставит игру на паузу при входе; следующая смена эпизода сама паузу не снимает.", "Pauses play on entry; another episode does not automatically unpause it."],
    ["sound", "sound", "Звук при входе", "Entry sound", "Путь к звуковому файлу, проигрываемому один раз при входе. Пустое поле — без звука.", "Audio file to play once on entry. Leave empty for no sound."]
  ] },
  { id: "settings-npc", ru: "НИП: состояние и реплики", en: "NPC state and speech", fields: [
    ["enabled", "enabled", "Выполнять автоматизацию токена в этом эпизоде", "Run this token's automation in this episode", "Разрешает подготовленное поведение. Ручное отключение в Режиссёре имеет приоритет.", "Enables the prepared behavior. A manual disable in Director takes precedence."],
    ["emoji", "emoji", "Эмоджи над токеном", "Emoji above the token", "Знак настроения для этого эпизода; пустое поле убирает эмоджи Ширмы.", "The mood indicator for this episode; an empty field removes the Master screen emoji."],
    ["positionEnabled", "position", "Устанавливать подготовленную позицию при входе", "Set the prepared position on entry", "Включите, чтобы новый вход возвращал токен в заданную точку. Переподключение не перемещает его.", "Enable to return the token to its planned position on a new entry. Reconnecting does not move it."],
    ["positionX", "position-x", "X, пиксели", "X, pixels", "Горизонтальная координата левого верхнего угла токена на карте.", "Horizontal map coordinate of the token's top-left corner."],
    ["positionY", "position-y", "Y, пиксели", "Y, pixels", "Вертикальная координата левого верхнего угла токена на карте.", "Vertical map coordinate of the token's top-left corner."],
    ["hidden", "visibility", "Видимость токена", "Token visibility", "Сохранить текущее состояние, показать игрокам или скрыть при входе в эпизод.", "Keep the current state, show to players or hide on episode entry."],
    ["entrySpeech", "entry-speech", "Однократная реплика при входе", "One-time entry line", "НИП произносит её один раз при каждом явном входе. Пустое поле отключает реплику.", "The NPC says this once on each explicit entry. Leave empty to disable it."],
    ["phrases", "phrases", "Периодические фразы", "Recurring phrases", "По одной фразе на строку; выбирается случайная. Пустой список отключает периодическую речь.", "One phrase per line; a random phrase is selected. An empty list disables recurring speech."],
    ["speechInterval", "interval", "Интервал, секунды", "Interval, seconds", "Время между периодическими репликами, от одной секунды. На паузе реплики приостанавливаются.", "Time between recurring lines, at least one second. Speech is suspended while the game is paused."],
    ["speechRange", "range", "Дальность, единицы сцены", "Range, scene units", "Реплики получают владельцы персонажей в пределах этой дальности, а также мастера.", "Players owning characters within this range receive the lines, as do GMs."],
    ["visibleOnly", "visible", "Реплики слышат только персонажи, которые видят НИП", "Only characters who can see the NPC hear speech", "Добавляет к дальности проверку включённого зрения и прямой видимости через стены. Освещение и особое зрение не учитываются. Выключите, если достаточно близости.", "Adds enabled sight and an unobstructed line through walls to the range check. Lighting and special senses are not evaluated. Disable when proximity alone is enough."]
  ] },
  { id: "settings-patrol", ru: "НИП: патрулирование", en: "NPC patrol settings", fields: [
    ["patrolEnabled", "enabled", "Двигаться по маршруту по кругу", "Patrol the route repeatedly", "Включает движение по опорным точкам в этом эпизоде. Пауза и ручное отключение останавливают патруль.", "Enables movement along the waypoints in this episode. Pause and manual disabling suspend patrol."],
    ["patrolSpeed", "speed", "Скорость, единицы сцены в секунду", "Speed, scene units per second", "Задаёт скорость перемещения НИП по маршруту.", "Controls the NPC's travel speed along the route."],
    ["points", "points", "Опорные точки", "Waypoints", "По строке на точку: x, y в пикселях. Удобнее добавлять точки кликом на карте. Необязательные поля после | — макрос проверки и эпизод: если проверка возвращает true, выполняется переход; иначе патруль продолжает путь.", "One point per line: x, y in pixels. Add points by clicking the map for convenience. Optional fields after | select a check macro and episode: returning true transitions, otherwise patrol continues."]
  ] },
  { id: "settings-shop", ru: "Настройки магазина", en: "Shop settings", fields: [
    ["shopEnabled", "enabled", "Предложить игроку обмен предметами", "Offer item trading to players", "Показывает магазин при взаимодействии с НИП в этом эпизоде.", "Makes the shop available when interacting with this NPC in the episode."],
    ["shopRange", "range", "Дальность взаимодействия, единицы сцены", "Interaction range, scene units", "Персонаж должен находиться не дальше этого расстояния от НИП.", "The character must be within this distance of the NPC."],
    ["shopApproval", "approval", "Обмен требует подтверждения мастера", "Trade requires GM approval", "Включено: игрок отправляет подготовленную сделку мастеру. Выключено: подтверждает самостоятельно.", "On: the player submits the prepared trade to the GM. Off: the player confirms it independently."],
    ["shopDisplay", "display", "Вид ассортимента", "Catalog display", "Список группирует товары по типу; плитки показывают миниатюры.", "List groups items by type; tiles display thumbnails."],
    ['[name^="stock-"]', "stock", "Запас", "Stock", "Количество доступных целых предметов данного образца. Это не число единиц внутри системного предмета; потраченный запас не восстанавливается сменой эпизода.", "Number of complete items available from this entry. This is not the quantity inside a system item; changing episodes does not restore spent stock."]
  ] },
  { id: "settings-trigger", ru: "Условия запуска", en: "Trigger conditions", fields: [
    ['[data-trigger-fields] [name$="-enabled"]', "enabled", "Разрешать запуск", "Allow activation", "Включает проверку условий триггера. Ручное отключение в Режиссёре действует до вашего включения.", "Enables the trigger's condition checks. A manual disable in Director persists until you enable it."],
    ['[data-trigger-fields] [name$="-scheme"]', "scheme", "Схема", "Scheme", "Ограничивает запуск отмеченными схемами. Пустой выбор не вводит ограничения.", "Restricts activation to selected schemes. An empty selection adds no restriction."],
    ['[data-trigger-fields] [name$="-episode"]', "episodes", "Эпизоды", "Episodes", "Ограничивает запуск отмеченными эпизодами. Пустой выбор не вводит ограничения; само взаимодействие остаётся в своём эпизоде.", "Restricts activation to selected episodes. An empty selection adds no restriction; the interaction still belongs to its own episode."],
    ['[data-trigger-fields] [name$="-allow"]', "allow", "Разрешающие теги, через запятую", "Allowed tags, comma-separated", "Достаточно любого совпадения с тегами действующего персонажа. Пусто — без ограничения.", "Any match with the acting character's tags is sufficient. Empty means unrestricted."],
    ['[data-trigger-fields] [name$="-deny"]', "deny", "Запрещающие теги, через запятую", "Denied tags, comma-separated", "Любое совпадение исключает персонажа даже при наличии разрешающего тега.", "Any match excludes the character, even if an allowed tag also matches."],
    ['[data-trigger-fields] [name$="-repeat"]', "repeat", "Повторение", "Repetition", "«Ограниченное число запусков» использует лимит; «Каждый раз» снимает предел.", "Limited activations uses the limit; Every time removes the cap."],
    ['[data-trigger-fields] [name$="-limit"]', "limit", "Лимит запусков", "Activation limit", "Число успешных запусков всего триггера, по умолчанию один. Не является отдельным лимитом для каждого игрока.", "The trigger's total successful activations, one by default. This is not a separate allowance per player."],
    ['[data-trigger-fields] [name$="-reset"]', "reset", "Сбрасывать счётчик при новом входе в эпизод", "Reset the counter on episode entry", "Включено: явный вход возвращает допуск. Выключено: сброс только вручную. Переподключение не сбрасывает счётчик.", "On: explicit entry restores the allowance. Off: reset manually. Reconnecting never resets the counter."]
  ] },
  { id: "settings-dialogue", ru: "Настройки диалога", en: "Dialogue settings", fields: [
    ["dialogueName", "name", "Название", "Name", "Название диалога в списках мастера и взаимодействиях.", "The dialogue's name in GM lists and interactions."],
    ["dialogueTarget", "target", "Объект взаимодействия", "Interaction object", "НИП или тайл, с которым связывается разговор.", "The NPC or tile that provides the conversation."],
    ["dialogueEnabled", "enabled", "Диалог доступен в эпизоде", "Dialogue available in the episode", "Включает обычное взаимодействие. Ручной просмотр мастером остаётся отдельным действием.", "Enables normal interaction. The GM's manual preview remains a separate action."],
    ["dialogueRange", "range", "Дальность, единицы сцены", "Range, scene units", "Максимальная дистанция персонажа до объекта для разговора.", "Maximum distance between the character and object to start a conversation."],
    ["dialogueStart", "start", "Начальная страница", "Starting page", "С этой страницы начинается новый разговор.", "A new conversation starts at this page."],
    ["nodeText", "text", "Реплика", "Line", "Текст НИП или описание предмета на текущей странице; вводите обычный текст.", "The NPC's line or object description on this page; enter plain text."],
    ["nodeArt", "art", "Иллюстрация страницы", "Page illustration", "Путь к изображению; пустое поле использует изображение объекта.", "Image path; an empty field uses the object's image."],
    ["responseLabel", "reply", "Текст ответа", "Reply text", "Название кнопки, которую выбирает игрок.", "The label of the reply button the player chooses."],
    ["responseNext", "next", "Следующая страница", "Next page", "Открывает выбранную страницу или завершает диалог.", "Opens the selected page or ends the conversation."],
    ["responseEvent", "event", "Сообщить событие", "Emit an event", "Имя события при завершении ответа, например guard.warned. Для этого оставьте «Завершить диалог» в следующей странице.", "Event name emitted when ending with this reply, for example guard.warned. Select End dialogue as the next page to use it."]
  ] },
  { id: "settings-actions", ru: "Настройки взаимодействия", en: "Interaction settings", fields: [
    ["objectTags", "tags", "Теги объекта", "Object tags", "Введите теги через запятую и сохраните. Они описывают объект этой сцены; регистр не учитывается.", "Enter comma-separated tags and save. They describe this scene's object; matching is case-insensitive."],
    ["actionName", "name", "Название действия", "Action name", "Название выбора, который увидит игрок при взаимодействии.", "The choice displayed to a player during interaction."],
    ["actionEnabled", "enabled", "Доступно", "Available", "Показывает прямое действие в выбранном эпизоде, если остальные условия соблюдены.", "Shows the direct action in the selected episode when other conditions pass."],
    ["actionTarget", "target", "Объект", "Object", "НИП или тайл, на котором доступно действие.", "The NPC or tile that offers the action."],
    ["actionRange", "range", "Дальность, единицы сцены", "Range, scene units", "Персонаж должен подойти к объекту на эту дистанцию.", "The character must approach the object within this distance."],
    ["actionEvent", "event", "Событие", "Event", "Имя, связывающее действие с реакцией; например lever.used. Используйте одинаковое имя в подписке.", "A name connecting the action to a reaction, such as lever.used. Use the same name in the subscription."],
    ["interactionLabel", "transition-label", "Название действия для игрока", "Player action label", "Как назвать действие НИП, которое переключает эпизод.", "The label for an NPC interaction that changes the episode."],
    ["interactionTarget", "transition-target", "Переход в эпизод", "Transition to episode", "Эпизод для действия НИП. «Без перехода» убирает этот выбор. Подготовленная связь получает своё событие перехода.", "The target episode for the NPC action. No transition removes this choice. The prepared connection receives its own transition event."]
  ] },
  { id: "settings-events", ru: "Реакции и сообщения", en: "Reactions and messages", fields: [
    ["subscriptionEnabled", "enabled", "Подписка включена", "Subscription enabled", "Разрешает реакцию на событие в активном эпизоде.", "Enables this event reaction in the active episode."],
    ["subscriptionEvent", "event", "Имя события", "Event name", "Должно точно совпадать с именем источника. Допустимы строчная латиница, цифры, точки, дефис и подчёркивание.", "Must exactly match the source name. Use lowercase Latin letters, digits, dots, hyphens and underscores."],
    ["subscriptionKind", "reaction", "Реакция", "Reaction", "Выберите одно действие: перейти в эпизод, запустить макрос или сообщить в чат.", "Choose one action: transition, run a macro or send a chat message."],
    ["subscriptionEpisode", "episode", "Цель для перехода", "Transition target", "Целевой эпизод, когда выбрана реакция перехода.", "The destination episode when the reaction is a transition."],
    ["subscriptionMacro", "macro", "UUID для макроса", "Macro UUID", "Укажите существующий проверенный макрос мастера для реакции «Запустить макрос».", "Select an existing GM macro you have checked for the Run macro reaction."],
    ["subscriptionText", "text", "Текст сообщения", "Message text", "Сообщение для выбранных ниже получателей.", "The message for the recipients chosen below."],
    ["audienceGMs", "gms", "Мастерам", "GMs", "Добавляет мастеров к получателям сообщения.", "Includes GMs among the message recipients."],
    ["audienceInteractor", "interactor", "Участнику действия", "Acting player", "Добавляет игрока, совершившего взаимодействие.", "Includes the player who performed the interaction."],
    ["audienceNearby", "nearby", "Персонажам рядом", "Nearby characters", "Добавляет владельцев персонажей в указанной дальности. Группы получателей объединяются.", "Includes owners of characters within the specified range. Recipient groups are combined."],
    ["audienceRange", "range", "Дальность для персонажей рядом", "Nearby character range", "Ограничение расстояния для группы «Персонажам рядом» в единицах сцены.", "The distance limit for Nearby characters, in scene units."],
    ["audienceVisible", "visible", "Рядом и в пределах линии видимости", "Nearby and in line of sight", "Добавляет проверку видимости для ближайших персонажей. Пустой список получателей не отправляет сообщение всем.", "Adds a visibility check for nearby characters. An empty recipient list does not broadcast to everyone."]
  ] },
  { id: "settings-map", ru: "Подкрепление и зоны", en: "Reinforcements and zones", fields: [
    ["spawnActor", "actor", "UUID персонажа", "Actor UUID", "Персонаж, из которого создаются токены подкрепления. Его можно перетащить из боковой панели.", "The Actor used for reinforcement tokens. Drag it from the sidebar to select it."],
    ["spawnX", "spawn-x", "X, пикс.", "X, pixels", "Горизонтальная координата первого токена подкрепления; можно указать на карте.", "Horizontal coordinate of the first reinforcement token; select it on the map if preferred."],
    ["spawnY", "spawn-y", "Y, пикс.", "Y, pixels", "Вертикальная координата первого токена подкрепления.", "Vertical coordinate of the first reinforcement token."],
    ["spawnCount", "count", "Количество", "Count", "Сколько токенов появится при входе, от 1 до 50. Новый вход может добавить подкрепление снова.", "Number of tokens spawned on entry, from 1 to 50. Another entry may add reinforcements again."],
    ["spawnSpacing", "spacing", "Шаг, пикс.", "Spacing, pixels", "Шаг размещения токенов подкрепления от выбранной точки.", "Spacing between reinforcement tokens from the selected position."],
    ["zoneLabel", "label", "Название зоны", "Zone name", "Понятное мастеру название для списка зон и триггеров.", "A recognizable name for zone and trigger lists."],
    ["zoneX", "zone-x", "X, пикс.", "X, pixels", "Левый край прямоугольной зоны на карте.", "The rectangular zone's left edge on the map."],
    ["zoneY", "zone-y", "Y, пикс.", "Y, pixels", "Верхний край прямоугольной зоны на карте.", "The rectangular zone's top edge on the map."],
    ["zoneWidth", "width", "Ширина", "Width", "Ширина зоны в пикселях карты.", "Zone width in map pixels."],
    ["zoneHeight", "height", "Высота", "Height", "Высота зоны в пикселях карты.", "Zone height in map pixels."],
    ["zoneTarget", "target", "Перейти в эпизод", "Transition to episode", "Эпизод при входе персонажа игрока в зону. Подготовленная связь получает событие перехода; условия запуска зоны сохраняются.", "The destination when a player character enters the zone. The prepared connection receives a transition event; the zone's activation conditions still apply."]
  ] },
  { id: "settings-windows", ru: "План рабочих окон", en: "Workspace window plan", fields: [
    ["windowUuid", "document", "UUID документа", "Document UUID", "Документ для показа при входе в эпизод. Проще перетащить лист в блок окон; игроку нужны права на документ.", "Document to show on entry. Drag a sheet into the window group for convenience; players need permission to view it."],
    ["windowX", "x", "X", "X", "Положение окна слева в пикселях экрана.", "The window's left position in screen pixels."],
    ["windowY", "y", "Y", "Y", "Положение окна сверху в пикселях экрана.", "The window's top position in screen pixels."],
    ["windowWidth", "width", "Ширина", "Width", "Подготовленная ширина окна в пикселях, от 100.", "Prepared window width in pixels, at least 100."],
    ["windowHeight", "height", "Высота", "Height", "Подготовленная высота окна в пикселях, от 100.", "Prepared window height in pixels, at least 100."]
  ] }
];

export function getScreenHelpContent(language = globalThis.game?.i18n?.lang) {
  const ru = String(language ?? "en").toLowerCase().startsWith("ru");
  const title = value => value[ru ? "ru" : "en"];
  const pages = SCREEN_HELP_PAGES.map(value => ({ id: value.id, title: title(value), html: value.sections.map(s => `<section><h3 id="${s.id}">${title(s)}</h3><p>${s[ru ? "bodyRu" : "bodyEn"]}</p></section>`).join("") }));
  pages.push(...SCREEN_HELP_SETTINGS.map(value => ({ id: value.id, title: title(value), html: value.fields.map(f => `<section><h3 id="${f[1]}">${f[ru ? 2 : 3]}</h3><p>${f[ru ? 4 : 5]}</p></section>`).join("") })));
  const entry = id => ({ id, pageId: id, title: pages.find(p => p.id === id).title });
  return { pages, footer: ["author", "thanks", "modules"], labels: { contents: ru ? "Содержание" : "Contents", resizeNavigation: ru ? "Изменить ширину меню" : "Resize navigation" }, tree: [
    { id: "prepare", title: ru ? "Подготовка" : "Preparation", children: ["start", "constructor", "objects", "catalog-tools", "events", "macros", "npc", "dialogues", "triggers", "workspace", "transfer"].map(entry) },
    { id: "play", title: ru ? "Проведение игры" : "Running the game", children: ["director", "stop", "trade", "actor"].map(entry) },
    { id: "settings", title: ru ? "Настройки" : "Settings", children: SCREEN_HELP_SETTINGS.map(p => entry(p.id)) }
  ] };
}

export function getScreenSettingHelp(language = globalThis.game?.i18n?.lang) {
  const ru = String(language ?? "en").toLowerCase().startsWith("ru");
  return SCREEN_HELP_SETTINGS.flatMap(p => p.fields.map(f => ({
    selector: f[0].startsWith("[") ? f[0] : `[name="${f[0]}"]`, pageId: p.id, anchor: f[1],
    hint: f[ru ? 4 : 5], label: ru ? `Справка: ${f[2]}` : `Help: ${f[3]}`
  })));
}
