// User documentation belongs to Master screen; Generics only displays it.
const section = (id, ru, en, bodyRu, bodyEn) => ({ id, ru, en, bodyRu, bodyEn });
const page = (id, ru, en, sections) => ({ id, ru, en, sections });
export const SCREEN_HELP_PAGES = [
  page("start", "Подготовить сцену к игре", "Prepare a scene for play", [
    section("prepare", "Карта и участники", "Map and participants", "Создайте сцену, добавьте карту и НИП обычными средствами Foundry. Откройте эту карту и выберите категорию ▥ Ширма, затем «Конструктор». Нажатие на категорию открывает только список кнопок.", "Create a scene, add its map and NPCs with Foundry, then view that map. Select the ▥ Master screen category and choose Constructor. The category itself only opens its buttons."),
    section("episodes", "От подготовки к запуску", "From preparation to play", "Настройте эпизоды «Спокойствие», «Напряжение», «Тревога» и «Остановка». Сохраните эпизод и поведение НИП. Сохранение не запускает подготовленные действия. Для запуска перейдите в «Режиссёр» и выберите эпизод.", "Prepare Calm, Tension, Alarm and Stop episodes. Save each episode and its NPC behavior. Saving does not run the prepared actions. Open Director and select an episode to start it."),
    section("next", "Что настроить дальше", "Next steps", '<a data-help-page="constructor">Переходы эпизодов</a> · <a data-help-page="npc">Поведение НИП</a> · <a data-help-page="stop">Ручное управление</a>', '<a data-help-page="constructor">Episode transitions</a> · <a data-help-page="npc">NPC behavior</a> · <a data-help-page="stop">Manual control</a>')
  ]),
  page("constructor", "Подготовить эпизоды", "Prepare episodes", [
    section("panel", "Освободить карту", "Keep the map clear", "Конструктор открывается панелью рядом со столом. В верхней строке выберите расположение справа или снизу; перетаскивайте границу, чтобы изменить размер. При закрытии панели стол снова занимает всю доступную область.", "Constructor docks beside the tabletop. Use its top bar to dock right or bottom, and drag the divider to resize it. Closing the panel restores the available tabletop area."),
    section("graph", "Разрешить нужные переходы", "Allow the right transitions", "Первым показан граф эпизодов. Нажмите эпизод, чтобы редактировать его. «Разрешить вход со всех эпизодов» допускает любой источник; выключите галку и отметьте конкретные входы, чтобы ограничить переходы.", "The episode graph is shown first. Select an episode to edit it. Allow entry from all episodes permits any source; clear it and select specific sources to restrict transitions."),
    section("text", "Задать связи текстом", "Enter transitions as text", "В «Переходы текстом» пишите по одной связи на строку: <code>calm -&gt; tension</code>. <code>* -&gt; alarm</code> разрешает вход отовсюду. Используйте точные имена или ID эпизодов. Проверьте предпросмотр: «Применить переходы» заменяет весь набор связей.", "In Transitions as text, enter one link per line: <code>calm -&gt; tension</code>. <code>* -&gt; alarm</code> allows entry from anywhere. Use exact names or episode IDs. Check the preview: Apply transitions replaces the complete set of links."),
    section("scene", "Сменить карту", "Switch maps", "Панель следует открытой карте. Сохраните или отмените незавершённый ввод перед сменой контекста. Сейчас для каждой сцены доступна одна основная схема.", "The panel follows the viewed map. Save or discard unsaved edits before changing context. Each scene currently has one main scheme.")
  ]),
  page("npc", "Оживить НИП", "Bring NPCs to life", [
    section("calm", "Реплики и торговля", "Speech and trading", "В Конструкторе выберите «Спокойствие» и нажмите НИП на карте левой кнопкой. Введите периодические фразы, интервал и дальность. При необходимости включите обмен и наполните ассортимент перетаскиванием предметов. Для постоянно доступного магазина задайте повторение «Каждый раз».", "Select Calm in Constructor and left-click the NPC on the map. Enter recurring phrases, interval and range. Enable trading if needed and drag items into the catalog. Set repetition to Every time for a shop that should remain available."),
    section("tension", "Предупреждение и патруль", "Warning and patrol", "В «Напряжении» задайте эмоджи и однократную реплику. Включите патрулирование, укажите скорость и добавьте точки кликами по карте. Поведения предыдущего эпизода прекращаются при переходе.", "In Tension, set an emoji and an entry line. Enable patrol, choose a speed and add waypoints by clicking the map. The previous episode's behaviors end on transition."),
    section("alarm", "Тревога и подкрепление", "Alarm and reinforcements", "В «Тревоге» включите паузу, выберите звук и добавьте подкрепление из списка персонажей. Укажите места и число НИП. В Режиссёре кнопка «Бой и инициатива» помогает подготовить бой. Завершение боя не выбирает следующий эпизод за мастера.", "In Alarm, enable pause, choose a sound and drag reinforcements from the Actors list. Set their positions and counts. In Director, Combat and initiative helps prepare combat. Ending combat does not choose the next episode for you.")
  ]),
  page("director", "Вести сцену", "Run the scene", [
    section("transition", "Переключить эпизод", "Switch episodes", "Откройте «Режиссёр», выберите эпизод из списка и нажмите «Перейти». Недоступные по графу переходы помечены. Явный повторный вход заново применяет подготовленные позиции, окна и разовые действия; перезагрузка Foundry этого не делает.", "Open Director, select an episode and press Transition. Links blocked by the graph are marked. Explicit re-entry reapplies prepared positions, windows and entry actions; reloading Foundry does not."),
    section("manual", "Вмешаться в игру", "Intervene in play", "Перемещайте токены и окна по ходу игры. Чтобы патруль не вернул НИП под управление, нажмите «Отключить» рядом с ним. Это отключение сохраняется между эпизодами до вашего прямого включения.", "Move tokens and windows as play unfolds. Press Disable beside an NPC to prevent its patrol from taking control again. This override persists across episodes until you explicitly enable it."),
    section("observe", "Проверить происходящее", "Check what is happening", "В Режиссёре доступны счётчики триггеров и журнал событий. Окна «Магазины» и «Диалоги и действия» позволяют подключиться к взаимодействию и прочитать нужную реплику.", "Director provides trigger counters and the event log. Shops and Dialogues and actions let you join an interaction or read the relevant line.")
  ]),
  page("stop", "Остановить автоматизацию", "Stop automation", [
    section("emergency", "Вернуть сцену под ручное управление", "Take manual control", "Нажмите заметную кнопку «Остановить всю автоматизацию сцены» в Режиссёре. Остановка сохраняется, а положение, здоровье и предметы остаются как есть. Закрытие окон Ширмы само по себе не останавливает сцену.", "Press Stop all scene automation in Director. The stop persists and positions, health and items remain as they are. Closing Master screen windows does not itself stop the scene."),
    section("resume", "Продолжить с выбранного момента", "Resume from a chosen point", "Выберите эпизод в поле возобновления и нажмите «Возобновить основную схему». Это новый вход: реплика, звук и подкрепление могут выполниться снова. Остановку отдельной схемы можно использовать независимо от общей кнопки.", "Choose a resume episode and press Resume main scheme. This is a new entry: speech, sound and reinforcements may run again. You can also stop the individual scheme independently of the scene-wide button."),
    section("facts", "После боя", "After combat", "При необходимости вручную перейдите в эпизод «Остановка». Он не лечит НИП, не возвращает товары и не убирает созданное подкрепление. Уже выполненные действия и начатый сторонний макрос кнопка остановки не отменяет.", "If appropriate, manually enter the Stop episode. It does not heal NPCs, restore goods or remove spawned reinforcements. The stop button cannot undo completed actions or cancel an already-running external macro.")
  ]),
  page("trade", "Провести обмен", "Trade items", [
    section("prepare", "Открыть магазин", "Open a shop", "Подведите своего персонажа к НИП и выберите взаимодействие магазина. Слева видны НИП и ассортимент; в зоне торговли подготовьте отдельно предложение персонажа и предложение магазина.", "Move your character near the NPC and choose its shop interaction. The NPC and catalog appear on the left; prepare the character's and shop's offers separately in the trade area."),
    section("confirm", "Подтвердить сделку", "Confirm the trade", "До подтверждения вещи остаются на своих местах. Нельзя предложить чужие вещи или отсутствующий товар. Один магазин обслуживает одного игрока с одним персонажем. Если нужно одобрение, отправьте запрос мастеру; иначе завершите обмен самостоятельно.", "Items stay in place until confirmation. You cannot offer another character's belongings or unavailable stock. A shop serves one player with one character at a time. Request GM approval when required, or complete the trade yourself."),
    section("gm", "Помочь игроку", "Assist a player", "В Режиссёре откройте «Магазины», выберите текущую сделку и подключитесь к ней. Без поддержки денежной системы цены и валюта не показываются; передаются целые предметы, включая заданное системой количество внутри них.", "In Director, open Shops and join the current trade. Without currency support, prices and money are hidden; complete items are transferred, including any quantity stored in them by the game system.")
  ]),
  page("dialogues", "Дать игроку взаимодействие", "Give players an interaction", [
    section("prepare", "Подготовить разговор или предмет", "Prepare a conversation or object", "В Конструкторе добавьте диалог, выберите НИП или тайл, укажите дальность. Заполните текст, изображение и ответы. Ответ продолжает разговор либо завершает его с событием. «Уйти» доступно всегда и не выполняет событие завершения.", "Add a dialogue in Constructor, select an NPC or tile, and set its range. Add text, an image and replies. A reply continues the conversation or ends it with an event. Leave is always available and does not trigger the completion event."),
    section("action", "Обойтись без разговора", "Act without a conversation", "Добавьте прямое действие, например «Потянуть рычаг». Оно отправит указанное событие сразу. Ниже настройте реакцию на то же имя события: переход, макрос или сообщение в чат.", "Add a direct action such as Pull the lever. It emits the chosen event immediately. Add a reaction using the same event name: a transition, macro or chat message."),
    section("manual", "Зачитать или показать вручную", "Read or show it manually", "В Режиссёре откройте «Диалоги и действия». Просматривайте и зачитывайте страницы или покажите диалог выбранным игрокам, даже после остановки автоматизации. Ручной показ не запускает события и не возобновляет сцену.", "Open Dialogues and actions in Director. Read pages yourself or show a dialogue to selected players, even while automation is stopped. Manual presentations do not emit events or resume the scene.")
  ]),
  page("triggers", "Ограничить лишние срабатывания", "Limit unwanted triggers", [
    section("tags", "Различать участников", "Distinguish participants", "В Конструкторе задайте токенам и тайлам теги через запятую. Триггер проверяет теги действующего персонажа: достаточно одного разрешающего тега, но любой запрещающий отменяет допуск. Пустые списки не ограничивают запуск.", "Assign comma-separated tags to tokens and tiles in Constructor. A trigger checks the acting character's tags: one allowed match is enough, but any denied match excludes it. Empty lists do not restrict activation."),
    section("count", "Не повторять одно событие без нужды", "Avoid needless repetition", "По умолчанию разрешён один запуск. Для постоянных взаимодействий выберите «Каждый раз». Сброс при новом входе задаётся отдельно; переподключение счётчик сохраняет. Новый разговор или торговая сессия расходует один запуск, продолжение — нет.", "One activation is allowed by default. Choose Every time for recurring interactions. Reset on entry is a separate option; reconnecting preserves the counter. A new conversation or trade session uses one activation; continuing it does not."),
    section("reset", "Разрешить ещё одну попытку", "Allow another attempt", "В Режиссёре раскройте «Допуск и счётчики триггеров». Сбросьте нужный счётчик или вручную включите/выключите триггер. Ручное включение не отменяет ограничения по тегам и эпизодам.", "Expand Trigger permissions and counters in Director. Reset a counter or manually enable or disable a trigger. Manual enabling does not bypass tag or episode restrictions.")
  ]),
  page("workspace", "Подготовить рабочие окна", "Prepare workspace windows", [
    section("plan", "Показать нужные документы", "Show the right documents", "В эпизоде перетащите документы в «Рабочий стол мастера» или «Окна игроков», либо возьмите расположение открытых листов. У игроков откроются только доступные им документы: права задаются в Foundry.", "Drag documents into the episode's GM workspace or Player windows, or capture the positions of open sheets. Players only see documents they may access; permissions are set in Foundry."),
    section("during", "Передвинуть во время игры", "Move windows during play", "Меняйте расположение вручную. Подготовленные позиции возвращаются при новом входе в эпизод, а при переподключении сохраняется текущее расположение. Ранее открытые вами листы Ширма не закрывает.", "Adjust positions during play. Prepared positions return on a new episode entry; reconnecting retains the current layout. Master screen does not close sheets you had already opened yourself."),
    section("appearance", "Выбрать удобный вид", "Choose an appearance", "В настройках Foundry откройте dmicher Generics: общая тема и поведение окон действуют для всех окон dmicher у вас. Прилипание помогает выровнять окна; импорт собственного CSS доступен с Premium.", "Open dmicher Generics in Foundry settings. The shared theme and window behavior apply to all your dmicher windows. Snapping helps align windows; custom CSS import is available with Premium.")
  ]),
  page("actor", "Посмотреть глазами персонажа", "Preview a character's view", [
    section("view", "Проверить доступное взаимодействие", "Check available interactions", "Откройте «Актёр» и выберите персонажа игрока. Предпросмотр учитывает его зрение и доступные взаимодействия. Это вспомогательный вид: тайлы, эффекты освещения и исследованный туман могут отличаться от клиента игрока.", "Open Actor and select a player character. The preview uses their vision and available interactions. It is a simplified view: tiles, lighting effects and explored fog may differ from the player's client."),
    section("display", "Второй экран", "Second display", "В Foundry 14 можно отделить окно штатной кнопкой и переместить его на второй экран. В Foundry 13 штатного отделения нет.", "In Foundry 14, use the native detach button to move the window to a second display. Foundry 13 does not provide native window detachment.")
  ]),
  page("transfer", "Перенести подготовленную сцену", "Transfer a prepared scene", [
    section("export", "Сохранить подготовку", "Save the preparation", "В Конструкторе нажмите «Экспорт JSON». Файл содержит сцену, подготовленные эпизоды и связанные персонажи, журналы и макросы. Отдельные предметы и таблицы из рабочих окон перенесите отдельно и обновите ссылки. Карты, изображения и звуки также перенесите отдельно, сохранив пути к ним.", "Press Export JSON in Constructor. The file contains the scene, prepared episodes and linked Actors, Journals and Macros. Transfer standalone Items and RollTables used in workspace windows separately and update their links. Also transfer maps, images and audio separately, preserving their paths."),
    section("import", "Проверить перед запуском", "Check before running", "В другом мире той же игровой системы выберите «Импорт JSON». Создаются отдельные документы, а сцена не запускается автоматически. Проверьте изображения, ссылки, права и используемые макросы, затем включите нужный эпизод вручную.", "Choose Import JSON in another world using the same game system. Separate documents are created and the scene does not start automatically. Check images, links, permissions and any macros, then start the desired episode manually.")
  ]),
  page("author", "Автор", "Author", [section("contact", "dmicher abathur kubrow", "dmicher abathur kubrow", 'Сообщить о проблеме или предложить улучшение можно на <a href="https://github.com/dkubrow-dev/dmicher-master-screen/issues" target="_blank" rel="noopener noreferrer">странице Ширмы</a>. Опишите действие и результат, укажите версию Foundry.', 'Use the <a href="https://github.com/dkubrow-dev/dmicher-master-screen/issues" target="_blank" rel="noopener noreferrer">Master screen issue tracker</a> to report a problem or suggest an improvement. Include the action, its result and your Foundry version.')]),
  page("thanks", "Благодарности", "Thanks", [section("community", "Участникам игр и проверки", "Players and testers", "Спасибо мастерам и игрокам, которые проверяют Ширму в своих играх и делятся конкретными примерами. Такие наблюдения помогают уменьшать рутину за столом.", "Thank you to GMs and players who test Master screen in their games and share concrete examples. Your observations help reduce routine work at the table.")]),
  page("premium", "Премиальный модуль", "Premium module", [section("features", "Дополнить оформление", "Extend the appearance", "Базовые эпизоды, диалоги и обмен работают без Premium. С доступом Premium можно импортировать собственные стили в настройках Generics поверх выбранной общей темы. Доступ и лицензию проверьте в настройках dmicher Premium; после потери доступа встроенная тема продолжает работать.", "Basic episodes, dialogues and trading work without Premium. With Premium access, import custom styles in Generics settings on top of the shared theme. Check access and your license in dmicher Premium settings; the built-in theme remains available when access ends.")])
];

// [field name (or a selector), anchor, RU label, EN label, RU hint, EN hint].
export const SCREEN_HELP_SETTINGS = [
  { id: "settings-episode", ru: "Настройки эпизода", en: "Episode settings", fields: [
    ["name", "name", "Название", "Name", "Имя эпизода в графе и списке Режиссёра.", "The episode's name in the graph and Director list."],
    ["allowFromAll", "entry", "Разрешить вход со всех эпизодов", "Allow entry from all episodes", "Включено: допустим любой источник. Выключено: действуют отмеченные разрешённые входы.", "On: any source is allowed. Off: only the selected incoming episodes are allowed."],
    ["from", "incoming", "Разрешённые входы", "Allowed incoming episodes", "Отметьте эпизоды, из которых можно перейти сюда, когда общий вход отключён.", "Select episodes that may transition here when entry from all episodes is disabled."],
    ["stop", "stop", "Остановка автоматизации", "Stop automation", "Эпизод оставляет игру под ручным управлением без реплик, движения и входных действий. Состояние мира сохраняется.", "This episode leaves play under manual control without speech, movement or entry actions. The world's state is preserved."],
    ["pause", "pause", "Поставить Foundry на паузу", "Pause Foundry", "Ставит игру на паузу при входе; следующая смена эпизода сама паузу не снимает.", "Pauses play on entry; another episode does not automatically unpause it."],
    ["sound", "sound", "Звук при входе", "Entry sound", "Путь к звуковому файлу, проигрываемому один раз при входе. Пустое поле — без звука.", "Audio file to play once on entry. Leave empty for no sound."]
  ] },
  { id: "settings-npc", ru: "НИП: состояние и реплики", en: "NPC state and speech", fields: [
    ["enabled", "enabled", "Выполнять автоматизацию токена в этом эпизоде", "Run this token's automation in this episode", "Разрешает подготовленное поведение. Ручное отключение в Режиссёре имеет приоритет.", "Enables the prepared behavior. A manual disable in Director takes precedence."],
    ["emoji", "emoji", "Эмоджи над токеном", "Emoji above the token", "Знак настроения для этого эпизода; пустое поле убирает эмоджи Ширмы.", "The mood indicator for this episode; an empty field removes the Master screen emoji."],
    ["positionEnabled", "position", "Устанавливать подготовленную позицию при входе", "Set the prepared position on entry", "Включите, чтобы новый вход возвращал токен в заданную точку. Переподключение не перемещает его.", "Enable to return the token to its planned position on a new entry. Reconnecting does not move it."],
    ["positionX", "position-x", "X, пиксели", "X, pixels", "Горизонтальная координата левого верхнего угла токена на карте.", "Horizontal map coordinate of the token's top-left corner."],
    ["positionY", "position-y", "Y, пиксели", "Y, pixels", "Вертикальная координата левого верхнего угла токена на карте.", "Vertical map coordinate of the token's top-left corner."],
    ["hidden", "visibility", "Видимость токена", "Token visibility", "Сохранить текущее состояние, показать игрокам или скрыть при входе в эпизод.", "Keep the current state, show to players or hide on episode entry."],
    ["entrySpeech", "entry-speech", "Однократная реплика при входе", "One-time entry line", "НИП произносит её один раз при каждом явном входе. Пустое поле отключает реплику.", "The NPC says this once on each explicit entry. Leave empty to disable it."],
    ["phrases", "phrases", "Периодические фразы", "Recurring phrases", "По одной фразе на строку; выбирается случайная. Пустой список отключает периодическую речь.", "One phrase per line; a random phrase is selected. An empty list disables recurring speech."],
    ["speechInterval", "interval", "Интервал, секунды", "Interval, seconds", "Время между периодическими репликами, от одной секунды. На паузе реплики приостанавливаются.", "Time between recurring lines, at least one second. Speech is suspended while the game is paused."],
    ["speechRange", "range", "Дальность, единицы сцены", "Range, scene units", "Реплики получают владельцы персонажей в пределах этой дальности, а также мастера.", "Players owning characters within this range receive the lines, as do GMs."],
    ["visibleOnly", "visible", "Реплики слышат только персонажи, которые видят НИП", "Only characters who can see the NPC hear speech", "Добавляет к дальности проверку включённого зрения и прямой видимости через стены. Освещение и особое зрение не учитываются. Выключите, если достаточно близости.", "Adds enabled sight and an unobstructed line through walls to the range check. Lighting and special senses are not evaluated. Disable when proximity alone is enough."]
  ] },
  { id: "settings-patrol", ru: "НИП: патрулирование", en: "NPC patrol settings", fields: [
    ["patrolEnabled", "enabled", "Двигаться по маршруту по кругу", "Patrol the route repeatedly", "Включает движение по опорным точкам в этом эпизоде. Пауза и ручное отключение останавливают патруль.", "Enables movement along the waypoints in this episode. Pause and manual disabling suspend patrol."],
    ["patrolSpeed", "speed", "Скорость, единицы сцены в секунду", "Speed, scene units per second", "Задаёт скорость перемещения НИП по маршруту.", "Controls the NPC's travel speed along the route."],
    ["points", "points", "Опорные точки", "Waypoints", "По строке на точку: x, y в пикселях. Удобнее добавлять точки кликом на карте. Необязательные поля после | — макрос проверки и эпизод: если проверка возвращает true, выполняется переход; иначе патруль продолжает путь.", "One point per line: x, y in pixels. Add points by clicking the map for convenience. Optional fields after | select a check macro and episode: returning true transitions, otherwise patrol continues."]
  ] },
  { id: "settings-shop", ru: "Настройки магазина", en: "Shop settings", fields: [
    ["shopEnabled", "enabled", "Предложить игроку обмен предметами", "Offer item trading to players", "Показывает магазин при взаимодействии с НИП в этом эпизоде.", "Makes the shop available when interacting with this NPC in the episode."],
    ["shopRange", "range", "Дальность взаимодействия, единицы сцены", "Interaction range, scene units", "Персонаж должен находиться не дальше этого расстояния от НИП.", "The character must be within this distance of the NPC."],
    ["shopApproval", "approval", "Обмен требует подтверждения мастера", "Trade requires GM approval", "Включено: игрок отправляет подготовленную сделку мастеру. Выключено: подтверждает самостоятельно.", "On: the player submits the prepared trade to the GM. Off: the player confirms it independently."],
    ["shopDisplay", "display", "Вид ассортимента", "Catalog display", "Список группирует товары по типу; плитки показывают миниатюры.", "List groups items by type; tiles display thumbnails."],
    ['[name^="stock-"]', "stock", "Запас", "Stock", "Количество доступных целых предметов данного образца. Это не число единиц внутри системного предмета; потраченный запас не восстанавливается сменой эпизода.", "Number of complete items available from this entry. This is not the quantity inside a system item; changing episodes does not restore spent stock."]
  ] },
  { id: "settings-trigger", ru: "Условия запуска", en: "Trigger conditions", fields: [
    ['[data-trigger-fields] [name$="-enabled"]', "enabled", "Разрешать запуск", "Allow activation", "Включает проверку условий триггера. Ручное отключение в Режиссёре действует до вашего включения.", "Enables the trigger's condition checks. A manual disable in Director persists until you enable it."],
    ['[data-trigger-fields] [name$="-scheme"]', "scheme", "Схема", "Scheme", "Ограничивает запуск отмеченными схемами. Пустой выбор не вводит ограничения.", "Restricts activation to selected schemes. An empty selection adds no restriction."],
    ['[data-trigger-fields] [name$="-episode"]', "episodes", "Эпизоды", "Episodes", "Ограничивает запуск отмеченными эпизодами. Пустой выбор не вводит ограничения; само взаимодействие остаётся в своём эпизоде.", "Restricts activation to selected episodes. An empty selection adds no restriction; the interaction still belongs to its own episode."],
    ['[data-trigger-fields] [name$="-allow"]', "allow", "Разрешающие теги, через запятую", "Allowed tags, comma-separated", "Достаточно любого совпадения с тегами действующего персонажа. Пусто — без ограничения.", "Any match with the acting character's tags is sufficient. Empty means unrestricted."],
    ['[data-trigger-fields] [name$="-deny"]', "deny", "Запрещающие теги, через запятую", "Denied tags, comma-separated", "Любое совпадение исключает персонажа даже при наличии разрешающего тега.", "Any match excludes the character, even if an allowed tag also matches."],
    ['[data-trigger-fields] [name$="-repeat"]', "repeat", "Повторение", "Repetition", "«Ограниченное число запусков» использует лимит; «Каждый раз» снимает предел.", "Limited activations uses the limit; Every time removes the cap."],
    ['[data-trigger-fields] [name$="-limit"]', "limit", "Лимит запусков", "Activation limit", "Число успешных запусков всего триггера, по умолчанию один. Не является отдельным лимитом для каждого игрока.", "The trigger's total successful activations, one by default. This is not a separate allowance per player."],
    ['[data-trigger-fields] [name$="-reset"]', "reset", "Сбрасывать счётчик при новом входе в эпизод", "Reset the counter on episode entry", "Включено: явный вход возвращает допуск. Выключено: сброс только вручную. Переподключение не сбрасывает счётчик.", "On: explicit entry restores the allowance. Off: reset manually. Reconnecting never resets the counter."]
  ] },
  { id: "settings-dialogue", ru: "Настройки диалога", en: "Dialogue settings", fields: [
    ["dialogueName", "name", "Название", "Name", "Название диалога в списках мастера и взаимодействиях.", "The dialogue's name in GM lists and interactions."],
    ["dialogueTarget", "target", "Объект взаимодействия", "Interaction object", "НИП или тайл, с которым связывается разговор.", "The NPC or tile that provides the conversation."],
    ["dialogueEnabled", "enabled", "Диалог доступен в эпизоде", "Dialogue available in the episode", "Включает обычное взаимодействие. Ручной просмотр мастером остаётся отдельным действием.", "Enables normal interaction. The GM's manual preview remains a separate action."],
    ["dialogueRange", "range", "Дальность, единицы сцены", "Range, scene units", "Максимальная дистанция персонажа до объекта для разговора.", "Maximum distance between the character and object to start a conversation."],
    ["dialogueStart", "start", "Начальная страница", "Starting page", "С этой страницы начинается новый разговор.", "A new conversation starts at this page."],
    ["nodeText", "text", "Реплика", "Line", "Текст НИП или описание предмета на текущей странице; вводите обычный текст.", "The NPC's line or object description on this page; enter plain text."],
    ["nodeArt", "art", "Иллюстрация страницы", "Page illustration", "Путь к изображению; пустое поле использует изображение объекта.", "Image path; an empty field uses the object's image."],
    ["responseLabel", "reply", "Текст ответа", "Reply text", "Название кнопки, которую выбирает игрок.", "The label of the reply button the player chooses."],
    ["responseNext", "next", "Следующая страница", "Next page", "Открывает выбранную страницу или завершает диалог.", "Opens the selected page or ends the conversation."],
    ["responseEvent", "event", "Сообщить событие", "Emit an event", "Имя события при завершении ответа, например guard.warned. Для этого оставьте «Завершить диалог» в следующей странице.", "Event name emitted when ending with this reply, for example guard.warned. Select End dialogue as the next page to use it."]
  ] },
  { id: "settings-actions", ru: "Настройки взаимодействия", en: "Interaction settings", fields: [
    ["objectTags", "tags", "Теги объекта", "Object tags", "Введите теги через запятую и сохраните. Они описывают объект этой сцены; регистр не учитывается.", "Enter comma-separated tags and save. They describe this scene's object; matching is case-insensitive."],
    ["actionName", "name", "Название действия", "Action name", "Название выбора, который увидит игрок при взаимодействии.", "The choice displayed to a player during interaction."],
    ["actionEnabled", "enabled", "Доступно", "Available", "Показывает прямое действие в выбранном эпизоде, если остальные условия соблюдены.", "Shows the direct action in the selected episode when other conditions pass."],
    ["actionTarget", "target", "Объект", "Object", "НИП или тайл, на котором доступно действие.", "The NPC or tile that offers the action."],
    ["actionRange", "range", "Дальность, единицы сцены", "Range, scene units", "Персонаж должен подойти к объекту на эту дистанцию.", "The character must approach the object within this distance."],
    ["actionEvent", "event", "Событие", "Event", "Имя, связывающее действие с реакцией; например lever.used. Используйте одинаковое имя в подписке.", "A name connecting the action to a reaction, such as lever.used. Use the same name in the subscription."],
    ["interactionLabel", "transition-label", "Название действия для игрока", "Player action label", "Как назвать действие НИП, которое переключает эпизод.", "The label for an NPC interaction that changes the episode."],
    ["interactionTarget", "transition-target", "Переход в эпизод", "Transition to episode", "Эпизод для действия НИП. «Без перехода» убирает этот выбор. Разрешения графа продолжают действовать.", "The target episode for the NPC action. No transition removes this choice. Graph restrictions still apply."]
  ] },
  { id: "settings-events", ru: "Реакции и сообщения", en: "Reactions and messages", fields: [
    ["subscriptionEnabled", "enabled", "Подписка включена", "Subscription enabled", "Разрешает реакцию на событие в активном эпизоде.", "Enables this event reaction in the active episode."],
    ["subscriptionEvent", "event", "Имя события", "Event name", "Должно точно совпадать с именем источника. Допустимы строчная латиница, цифры, точки, дефис и подчёркивание.", "Must exactly match the source name. Use lowercase Latin letters, digits, dots, hyphens and underscores."],
    ["subscriptionKind", "reaction", "Реакция", "Reaction", "Выберите одно действие: перейти в эпизод, запустить макрос или сообщить в чат.", "Choose one action: transition, run a macro or send a chat message."],
    ["subscriptionEpisode", "episode", "Цель для перехода", "Transition target", "Целевой эпизод, когда выбрана реакция перехода.", "The destination episode when the reaction is a transition."],
    ["subscriptionMacro", "macro", "UUID для макроса", "Macro UUID", "Укажите существующий проверенный макрос мастера для реакции «Запустить макрос».", "Select an existing GM macro you have checked for the Run macro reaction."],
    ["subscriptionText", "text", "Текст сообщения", "Message text", "Сообщение для выбранных ниже получателей.", "The message for the recipients chosen below."],
    ["audienceGMs", "gms", "Мастерам", "GMs", "Добавляет мастеров к получателям сообщения.", "Includes GMs among the message recipients."],
    ["audienceInteractor", "interactor", "Участнику действия", "Acting player", "Добавляет игрока, совершившего взаимодействие.", "Includes the player who performed the interaction."],
    ["audienceNearby", "nearby", "Персонажам рядом", "Nearby characters", "Добавляет владельцев персонажей в указанной дальности. Группы получателей объединяются.", "Includes owners of characters within the specified range. Recipient groups are combined."],
    ["audienceRange", "range", "Дальность для персонажей рядом", "Nearby character range", "Ограничение расстояния для группы «Персонажам рядом» в единицах сцены.", "The distance limit for Nearby characters, in scene units."],
    ["audienceVisible", "visible", "Рядом и в пределах линии видимости", "Nearby and in line of sight", "Добавляет проверку видимости для ближайших персонажей. Пустой список получателей не отправляет сообщение всем.", "Adds a visibility check for nearby characters. An empty recipient list does not broadcast to everyone."]
  ] },
  { id: "settings-map", ru: "Подкрепление и зоны", en: "Reinforcements and zones", fields: [
    ["spawnActor", "actor", "UUID персонажа", "Actor UUID", "Персонаж, из которого создаются токены подкрепления. Его можно перетащить из боковой панели.", "The Actor used for reinforcement tokens. Drag it from the sidebar to select it."],
    ["spawnX", "spawn-x", "X, пикс.", "X, pixels", "Горизонтальная координата первого токена подкрепления; можно указать на карте.", "Horizontal coordinate of the first reinforcement token; select it on the map if preferred."],
    ["spawnY", "spawn-y", "Y, пикс.", "Y, pixels", "Вертикальная координата первого токена подкрепления.", "Vertical coordinate of the first reinforcement token."],
    ["spawnCount", "count", "Количество", "Count", "Сколько токенов появится при входе, от 1 до 50. Новый вход может добавить подкрепление снова.", "Number of tokens spawned on entry, from 1 to 50. Another entry may add reinforcements again."],
    ["spawnSpacing", "spacing", "Шаг, пикс.", "Spacing, pixels", "Шаг размещения токенов подкрепления от выбранной точки.", "Spacing between reinforcement tokens from the selected position."],
    ["zoneLabel", "label", "Название зоны", "Zone name", "Понятное мастеру название для списка зон и триггеров.", "A recognizable name for zone and trigger lists."],
    ["zoneX", "zone-x", "X, пикс.", "X, pixels", "Левый край прямоугольной зоны на карте.", "The rectangular zone's left edge on the map."],
    ["zoneY", "zone-y", "Y, пикс.", "Y, pixels", "Верхний край прямоугольной зоны на карте.", "The rectangular zone's top edge on the map."],
    ["zoneWidth", "width", "Ширина", "Width", "Ширина зоны в пикселях карты.", "Zone width in map pixels."],
    ["zoneHeight", "height", "Высота", "Height", "Высота зоны в пикселях карты.", "Zone height in map pixels."],
    ["zoneTarget", "target", "Перейти в эпизод", "Transition to episode", "Эпизод при входе персонажа игрока в зону. Также проверяются разрешения графа и условия запуска.", "Destination when a player character enters the zone. Graph permissions and trigger conditions are also checked."]
  ] },
  { id: "settings-windows", ru: "План рабочих окон", en: "Workspace window plan", fields: [
    ["windowUuid", "document", "UUID документа", "Document UUID", "Документ для показа при входе в эпизод. Проще перетащить лист в блок окон; игроку нужны права на документ.", "Document to show on entry. Drag a sheet into the window group for convenience; players need permission to view it."],
    ["windowX", "x", "X", "X", "Положение окна слева в пикселях экрана.", "The window's left position in screen pixels."],
    ["windowY", "y", "Y", "Y", "Положение окна сверху в пикселях экрана.", "The window's top position in screen pixels."],
    ["windowWidth", "width", "Ширина", "Width", "Подготовленная ширина окна в пикселях, от 100.", "Prepared window width in pixels, at least 100."],
    ["windowHeight", "height", "Высота", "Height", "Подготовленная высота окна в пикселях, от 100.", "Prepared window height in pixels, at least 100."]
  ] }
];

export function getScreenHelpContent(language = globalThis.game?.i18n?.lang) {
  const ru = String(language ?? "en").toLowerCase().startsWith("ru");
  const title = value => value[ru ? "ru" : "en"];
  const pages = SCREEN_HELP_PAGES.map(value => ({ id: value.id, title: title(value), html: value.sections.map(s => `<section><h3 id="${s.id}">${title(s)}</h3><p>${s[ru ? "bodyRu" : "bodyEn"]}</p></section>`).join("") }));
  pages.push(...SCREEN_HELP_SETTINGS.map(value => ({ id: value.id, title: title(value), html: value.fields.map(f => `<section><h3 id="${f[1]}">${f[ru ? 2 : 3]}</h3><p>${f[ru ? 4 : 5]}</p></section>`).join("") })));
  const entry = id => ({ id, pageId: id, title: pages.find(p => p.id === id).title });
  return { pages, footer: ["author", "thanks", "premium"], labels: { contents: ru ? "Содержание" : "Contents", resizeNavigation: ru ? "Изменить ширину меню" : "Resize navigation" }, tree: [
    { id: "prepare", title: ru ? "Подготовка" : "Preparation", children: ["start", "constructor", "npc", "dialogues", "triggers", "workspace", "transfer"].map(entry) },
    { id: "play", title: ru ? "Проведение игры" : "Running the game", children: ["director", "stop", "trade", "actor"].map(entry) },
    { id: "settings", title: ru ? "Настройки" : "Settings", children: SCREEN_HELP_SETTINGS.map(p => entry(p.id)) }
  ] };
}

export function getScreenSettingHelp(language = globalThis.game?.i18n?.lang) {
  const ru = String(language ?? "en").toLowerCase().startsWith("ru");
  return SCREEN_HELP_SETTINGS.flatMap(p => p.fields.map(f => ({
    selector: f[0].startsWith("[") ? f[0] : `[name="${f[0]}"]`, pageId: p.id, anchor: f[1],
    hint: f[ru ? 4 : 5], label: ru ? `Справка: ${f[2]}` : `Help: ${f[3]}`
  })));
}
